export const SELECTION__RESET_ROWS = 'SELECTION__RESET_ROWS'
export const SELECTION__TOGGLE_ALL = 'SELECTION__TOGGLE_ALL'
export const SELECTION__TOGGLE_ROW = 'SELECTION__TOGGLE_ROW'
export const SELECTION__TOGGLE_ENTIRE_ROWS = 'SELECTION__TOGGLE_ENTIRE_ROWS'
