export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const TOGGLE_FAVORITE_REQUEST = 'TOGGLE_FAVORITE_REQUEST'
export const TOGGLE_FAVORITE_SUCCESS = 'TOGGLE_FAVORITE_SUCCESS'
export const TOGGLE_FAVORITE_FAILURE = 'TOGGLE_FAVORITE_FAILURE'
