export const ADD_ATTACHMENTS = 'DEAL_ACTIONS__ADD_ATTACHMENTS'
export const CLEAR_ATTACHMENTS = 'DEAL_ACTIONS__CLEAR_ATTACHMENTS'
export const REMOVE_ATTACHMENT = 'DEAL_ACTIONS__REMOVE_ATTACHMENT'
export const SET_DRAWER_STATUS = 'DEAL_ACTIONS__SET_DRAWER_STATUS'
