export const BRAND_REQUEST = 'BRAND_REQUEST'
export const BRAND_SUCCESS = 'BRAND_SUCCESS'
export const BRAND_FAILURE = 'BRAND_FAILURE'

export const SET_ACTIVE_BRAND_VIEW_AS = 'SET_ACTIVE_BRAND_VIEW_AS'
