export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'

export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS'

export const MARK_NOTIFICATION_SEEN_SUCCESS = 'MARK_NOTIFICATION_SEEN_SUCCESS'

export const MARK_ALL_NOTIFICATIONS_SEEN_SUCCESS =
  'MARK_ALL_NOTIFICATIONS_SEEN_SUCCESS'
