export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT'

export const GET_PLACE_REQUEST = 'GET_PLACE_REQUEST'
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS'
export const GET_PLACE_FAILURE = 'GET_PLACE_FAILURE'

export const RESET_SEARCH_TYPE = 'RESET_SEARCH_TYPE'
export const SEARCH_BY_MAP_BOUNDS = 'SEARCH_BY_MAP_BOUNDS'
export const SEARCH_BY_MLS_NUMBER = 'SEARCH_BY_MLS_NUMBER'
export const SEARCH_BY_POSTAL_CODE = 'SEARCH_BY_POSTAL_CODE'
export const SEARCH_BY_FILTERS_AREAS = 'SEARCH_BY_FILTERS_AREAS'
export const SEARCH_BY_POLYGON_POINTS = 'SEARCH_BY_POLYGON_POINTS'
export const SEARCH_BY_GOOGLE_SUGGESTS = 'SEARCH_BY_GOOGLE_SUGGESTS'

export const SET_SEARCH_LISTINGS_OPTIONS = 'SET_SEARCH_LISTINGS_OPTIONS'
