export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE'

export const FETCH_CONTACT_ACTIVITIES_REQUEST =
  'FETCH_CONTACT_ACTIVITIES_REQUEST'
export const FETCH_CONTACT_ACTIVITIES_SUCCESS =
  'FETCH_CONTACT_ACTIVITIES_SUCCESS'
export const FETCH_CONTACT_ACTIVITIES_FAILURE =
  'FETCH_CONTACT_ACTIVITIES_FAILURE'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE'
