export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE'

export const FETCH_CONTACT_ATTR_DEFS_REQUEST = 'FETCH_CONTACT_ATTR_DEFS_REQUEST'
export const FETCH_CONTACT_ATTR_DEFS_SUCCESS = 'FETCH_CONTACT_ATTR_DEFS_SUCCESS'
export const FETCH_CONTACT_ATTR_DEFS_FAILURE = 'FETCH_CONTACT_ATTR_DEFS_FAILURE'

export const PATCH_CONTACT_REQUEST = 'PATCH_CONTACT_REQUEST'
export const PATCH_CONTACT_SUCCESS = 'PATCH_CONTACT_SUCCESS'
export const PATCH_CONTACT_FAILURE = 'PATCH_CONTACT_FAILURE'

export const FETCH_CONTACT_ACTIVITIES_REQUEST =
  'FETCH_CONTACT_ACTIVITIES_REQUEST'
export const FETCH_CONTACT_ACTIVITIES_SUCCESS =
  'FETCH_CONTACT_ACTIVITIES_SUCCESS'
export const FETCH_CONTACT_ACTIVITIES_FAILURE =
  'FETCH_CONTACT_ACTIVITIES_FAILURE'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE'

export const CLEAR_CONTACTS_LIST = 'CLEAR_CONTACTS_LIST'

export const UPDATE_CONTACT_LIST_INFO = 'UPDATE_CONTACT_LIST_INFO'
export const UPDATE_CONTACT_TAGS = 'UPDATE_CONTACT_TAGS'

export const SET_CONTACTS_LIST_TEXT_FILTER = 'SET_CONTACTS_LIST_TEXT_FILTER'

export const SEARCH_CONTACTS_REQUEST = 'SEARCH_CONTACTS_REQUEST'
export const SEARCH_CONTACTS_SUCCESS = 'SEARCH_CONTACTS_SUCCESS'
export const SEARCH_CONTACTS_FAILURE = 'SEARCH_CONTACTS_FAILURE'

export const FETCH_CONTACTS_TAGS_REQUEST = 'FETCH_CONTACTS_TAGS_REQUEST'
export const FETCH_CONTACTS_TAGS_SUCCESS = 'FETCH_CONTACTS_TAGS_SUCCESS'
export const FETCH_CONTACTS_TAGS_FAILURE = 'FETCH_CONTACTS_TAGS_FAILURE'

export const CREATE_CONTACTS_REQUEST = 'CREATE_CONTACTS_REQUEST'
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS'
export const CREATE_CONTACTS_FAILURE = 'CREATE_CONTACTS_FAILURE'

export const POST_NEW_ATTRIBUTES_REQUEST = 'POST_NEW_ATTRIBUTES_REQUEST'
export const POST_NEW_ATTRIBUTES_SUCCESS = 'POST_NEW_ATTRIBUTES_SUCCESS'
export const POST_NEW_ATTRIBUTES_FAILURE = 'POST_NEW_ATTRIBUTES_FAILURE'

export const DELETE_ATTRIBUTE_REQUEST = 'DELETE_ATTRIBUTE_REQUEST'
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS'
export const DELETE_ATTRIBUTE_FAILURE = 'DELETE_ATTRIBUTE_FAILURE'

export const DELETE_CONTACTS_REQUEST = 'DELETE_CONTACTS_REQUEST'
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS'
export const DELETE_CONTACTS_FAILURE = 'DELETE_CONTACTS_FAILURE'

// Import
export const CONTACTS__IMPORT_DONE = 'CONTACTS__IMPORT_DONE'
export const CONTACTS__SHOW_SPINNER = 'CONTACTS__SHOW_SPINNER'
export const CONTACTS__HIDE_SPINNER = 'CONTACTS__HIDE_SPINNER'
export const CONTACTS__IMPORT_FAIL_LOGIN = 'CONTACTS__IMPORT_FAIL_LOGIN'
export const CONTACTS__REMOVE_IMPORT_RESULT = 'CONTACTS__REMOVE_IMPORT_RESULT'
export const CONTACTS__IMPORT_SUCCESSFUL_LOGIN =
  'CONTACTS__IMPORT_SUCCESSFUL_LOGIN'

export const UPSERT_ATTRIBUTES_TO_CONTACTS_REQUEST =
  'UPSERT_ATTRIBUTES_TO_CONTACTS_REQUEST'
export const UPSERT_ATTRIBUTES_TO_CONTACTS_SUCCESS =
  'UPSERT_ATTRIBUTES_TO_CONTACTS_SUCCESS'
export const UPSERT_ATTRIBUTES_TO_CONTACTS_FAILURE =
  'UPSERT_ATTRIBUTES_TO_CONTACTS_FAILURE'

export const DELETE_ATTRIBUTES_FROM_CONTACTS_REQUEST =
  'DELETE_ATTRIBUTES_FROM_CONTACTS_REQUEST'
export const DELETE_ATTRIBUTES_FROM_CONTACTS_SUCCESS =
  'DELETE_ATTRIBUTES_FROM_CONTACTS_SUCCESS'
export const DELETE_ATTRIBUTES_FROM_CONTACTS_FAILURE =
  'DELETE_ATTRIBUTES_FROM_CONTACTS_FAILURE'

export const CREATE_CONTACT_ATTR_DEF_REQUEST = 'CREATE_CONTACT_ATTR_DEF_REQUEST'
export const CREATE_CONTACT_ATTR_DEF_SUCCESS = 'CREATE_CONTACT_ATTR_DEF_SUCCESS'
export const CREATE_CONTACT_ATTR_DEF_FAILURE = 'CREATE_CONTACT_ATTR_DEF_FAILURE'

export const FETCH_MERGE_CONTACTS_REQUEST = 'FETCH_MERGE_CONTACTS_REQUEST'
export const FETCH_MERGE_CONTACTS_SUCCESS = 'FETCH_MERGE_CONTACTS_SUCCESS'
export const FETCH_MERGE_CONTACTS_FAILURE = 'FETCH_MERGE_CONTACTS_FAILURE'

export const FETCH_OAUTH_ACCOUNTS_REQUEST = 'FETCH_OAUTH_ACCOUNTS_REQUEST'
export const FETCH_OAUTH_ACCOUNTS_SUCCESS = 'FETCH_OAUTH_ACCOUNTS_SUCCESS'
export const FETCH_OAUTH_ACCOUNTS_FAILURE = 'FETCH_OAUTH_ACCOUNTS_FAILURE'

export const FETCH_OAUTH_ACCOUNT_REQUEST = 'FETCH_OAUTH_ACCOUNT_REQUEST'
export const FETCH_OAUTH_ACCOUNT_SUCCESS = 'FETCH_OAUTH_ACCOUNT_SUCCESS'
export const FETCH_OAUTH_ACCOUNT_FAILURE = 'FETCH_OAUTH_ACCOUNT_FAILURE'

export const SYNC_OAUTH_ACCOUNT_REQUEST = 'SYNC_OAUTH_ACCOUNT_REQUEST'
export const SYNC_OAUTH_ACCOUNT_SUCCESS = 'SYNC_OAUTH_ACCOUNT_SUCCESS'
export const SYNC_OAUTH_ACCOUNT_FAILURE = 'SYNC_OAUTH_ACCOUNT_FAILURE'
export const DISCONNECT_OAUTH_ACCOUNT_REQUEST =
  'DISCONNECT_OAUTH_ACCOUNT_REQUEST'
export const DISCONNECT_OAUTH_ACCOUNT_SUCCESS =
  'DISCONNECT_OAUTH_ACCOUNT_SUCCESS'
export const DISCONNECT_OAUTH_ACCOUNT_FAILURE =
  'DISCONNECT_OAUTH_ACCOUNT_FAILURE'

export enum OAuthProvider {
  Google = 'google',
  Outlook = 'microsoft'
}
