export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE'

export const FETCH_CONTACT_ATTR_DEFS_REQUEST = 'FETCH_CONTACT_ATTR_DEFS_REQUEST'
export const FETCH_CONTACT_ATTR_DEFS_SUCCESS = 'FETCH_CONTACT_ATTR_DEFS_SUCCESS'
export const FETCH_CONTACT_ATTR_DEFS_FAILURE = 'FETCH_CONTACT_ATTR_DEFS_FAILURE'

export const PATCH_CONTACT_REQUEST = 'PATCH_CONTACT_REQUEST'
export const PATCH_CONTACT_SUCCESS = 'PATCH_CONTACT_SUCCESS'
export const PATCH_CONTACT_FAILURE = 'PATCH_CONTACT_FAILURE'

export const FETCH_CONTACT_ACTIVITIES_REQUEST =
  'FETCH_CONTACT_ACTIVITIES_REQUEST'
export const FETCH_CONTACT_ACTIVITIES_SUCCESS =
  'FETCH_CONTACT_ACTIVITIES_SUCCESS'
export const FETCH_CONTACT_ACTIVITIES_FAILURE =
  'FETCH_CONTACT_ACTIVITIES_FAILURE'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE'

export const CLEAR_CONTACTS_LIST = 'CLEAR_CONTACTS_LIST'

export const UPDATE_CONTACT_LIST_INFO = 'UPDATE_CONTACT_LIST_INFO'

export const SET_CONTACT_FILTERS = 'SET_CONTACT_FILTERS'

export const SEARCH_CONTACTS_REQUEST = 'SEARCH_CONTACTS_REQUEST'
export const SEARCH_CONTACTS_SUCCESS = 'SEARCH_CONTACTS_SUCCESS'
export const SEARCH_CONTACTS_FAILURE = 'SEARCH_CONTACTS_FAILURE'

export const FETCH_CONTACTS_TAGS_REQUEST = 'FETCH_CONTACTS_TAGS_REQUEST'
export const FETCH_CONTACTS_TAGS_SUCCESS = 'FETCH_CONTACTS_TAGS_SUCCESS'
export const FETCH_CONTACTS_TAGS_FAILURE = 'FETCH_CONTACTS_TAGS_FAILURE'

export const CREATE_CONTACTS_REQUEST = 'CREATE_CONTACTS_REQUEST'
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS'
export const CREATE_CONTACTS_FAILURE = 'CREATE_CONTACTS_FAILURE'

export const POST_NEW_ATTRIBUTES_REQUEST = 'POST_NEW_ATTRIBUTES_REQUEST'
export const POST_NEW_ATTRIBUTES_SUCCESS = 'POST_NEW_ATTRIBUTES_SUCCESS'
export const POST_NEW_ATTRIBUTES_FAILURE = 'POST_NEW_ATTRIBUTES_FAILURE'

export const DELETE_ATTRIBUTE_REQUEST = 'DELETE_ATTRIBUTE_REQUEST'
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS'
export const DELETE_ATTRIBUTE_FAILURE = 'DELETE_ATTRIBUTE_FAILURE'

export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE'

// Import
export const CONTACTS__IMPORT_DONE = 'CONTACTS__IMPORT_DONE'
export const CONTACTS__SHOW_SPINNER = 'CONTACTS__SHOW_SPINNER'
export const CONTACTS__HIDE_SPINNER = 'CONTACTS__HIDE_SPINNER'
export const CONTACTS__IMPORT_FAIL_LOGIN = 'CONTACTS__IMPORT_FAIL_LOGIN'
export const CONTACTS__REMOVE_IMPORT_RESULT = 'CONTACTS__REMOVE_IMPORT_RESULT'
export const CONTACTS__IMPORT_SUCCESSFUL_LOGIN =
  'CONTACTS__IMPORT_SUCCESSFUL_LOGIN'

export const CONTACTS__IMPORT_CSV__ADD_FILE = 'CONTACTS__IMPORT_CSV__ADD_FILE'
export const CONTACTS__IMPORT_CSV__SET_INFO = 'CONTACTS__IMPORT_CSV__SET_INFO'
export const CONTACTS__IMPORT_CSV__UPDATE_MAPPING =
  'CONTACTS__IMPORT_CSV__UPDATE_MAPPING'
export const CONTACTS__IMPORT_CSV__RESET = 'CONTACTS__IMPORT_CSV__RESET'
export const CONTACTS__IMPORT_CSV__UPDATE_WIZARD_STEP =
  'CONTACTS__IMPORT_CSV__UPDATE_WIZARD_STEP'
export const CONTACTS__IMPORT_CSV__SET_STEP_VALIDATION =
  'CONTACTS__IMPORT_CSV__SET_STEP_VALIDATION'
export const CONTACTS__IMPORT_CSV__SET_WORKER_ID =
  'CONTACTS__IMPORT_CSV__SET_WORKER_ID'
export const CONTACTS__IMPORT_CSV__SET_WORKER_STATE =
  'CONTACTS__IMPORT_CSV__SET_WORKER_STATE'
export const CONTACTS__IMPORT_CSV__SET_CSV_FILE =
  'CONTACTS__IMPORT_CSV__SET_CSV_FILE'

export const CONTACTS__IMPORT_CSV__STEP_SELECT_FILE = 0
export const CONTACTS__IMPORT_CSV__STEP_UPLOAD_FILE = 1
export const CONTACTS__IMPORT_CSV__STEP_MAP_FIELDS = 2
export const CONTACTS__IMPORT_CSV__STEP_UPLOAD_CONTACTS = 3
