export const UPDATE_USER = 'UPDATE_USER'
export const SET_USER_BRAND_MEMBERS = 'SET_USER_BRAND_MEMBERS'

export const FETCH_USER_TEAMS_REQUEST = 'FETCH_USER_TEAMS_REQUEST'
export const FETCH_USER_TEAMS_SUCCESS = 'FETCH_USER_TEAMS_SUCCESS'
export const FETCH_USER_TEAMS_FAILURE = 'FETCH_USER_TEAMS_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const UPLOAD_AVATAR_REQUEST = 'UPLOAD_AVATAR_REQUEST'
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'

export const UPLOAD_COVER_IMAGE_REQUEST = 'UPLOAD_COVER_IMAGE_REQUEST'
export const UPLOAD_COVER_IMAGE_SUCCESS = 'UPLOAD_COVER_IMAGE_SUCCESS'

export const UPGRADE_TO_AGENT_REQUEST = 'UPGRADE_TO_AGENT_REQUEST'
export const UPGRADE_TO_AGENT_SUCCESS = 'UPGRADE_TO_AGENT_SUCCESS'

export const POST_USER_ACTIVITY_REQUEST = 'POST_USER_ACTIVITY_REQUEST'
export const POST_USER_ACTIVITY_SUCCESS = 'POST_USER_ACTIVITY_SUCCESS'
export const POST_USER_ACTIVITY_FAILURE = 'POST_USER_ACTIVITY_FAILURE'

export const CHANGE_VIEW_AS_FILTER_REQUEST = 'CHANGE_VIEW_AS_FILTER_REQUEST'
export const CHANGE_VIEW_AS_FILTER_SUCCESS = 'CHANGE_VIEW_AS_FILTER_SUCCESS'
export const CHANGE_VIEW_AS_FILTER_FAILURE = 'CHANGE_VIEW_AS_FILTER_FAILURE'
