export const UPDATE_USER = 'UPDATE_USER'
export const SET_USER_BRANDS = 'SET_USER_BRANDS'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const UPLOAD_AVATAR_REQUEST = 'UPLOAD_AVATAR_REQUEST'
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'

export const UPLOAD_COVER_IMAGE_REQUEST = 'UPLOAD_COVER_IMAGE_REQUEST'
export const UPLOAD_COVER_IMAGE_SUCCESS = 'UPLOAD_COVER_IMAGE_SUCCESS'

export const UPGRADE_TO_AGENT_REQUEST = 'UPGRADE_TO_AGENT_REQUEST'
export const UPGRADE_TO_AGENT_SUCCESS = 'UPGRADE_TO_AGENT_SUCCESS'
