export default [
  'NO_DEAL',
  'GET_DEALS',
  'CREATE_DEAL',
  'UPDATE_DEAL',
  'UPDATE_LISTING',
  'ARCHIVE_DEAL',
  'GET_CHECKLISTS',
  'APPEND_CHECKLIST',
  'SET_ENVELOPES',
  'UPDATE_ROLES',
  'DELETE_ROLE',
  'SHOW_SPINNER',
  'HIDE_SPINNER',
  'ADD_SEARCHED_DEALS'

]
