export default [
  'SHOW_ATTACHMENTS',
  'SHOW_COMPOSE',
  'ADD_ATTACHMENT',
  'REMOVE_ATTACHMENT',
  'CLOSE_ESIGN_WIZARD',
  'CLOSE_ATTACHMENTS',
  'SET_ENVELOPE_STATUS',
  'SET_RECIPIENT',
  'CREATE_ENVELOPE',
  'REMOVE_RECIPIENT'
]
