export default [
  'SET_SPLITTER_DISPLAY',
  'SET_SPLITTER_PDF_OBJECT',
  'SELECT_SPLITTER_PAGE',
  'DESELECT_SPLITTER_PAGE',
  'SET_SPLITTER_USED_PAGES',
  'RESET_SPLITTER_PAGES',
  'SET_PAGE_PREVIEW',
  'RESET_SPLITTER'
]
