export default [
  'GET_TASKS',
  'CHANGE_TASK_STATUS',
  'CHANGE_ATTENTION_REQUESTED',
  'CREATE_TASK',
  'ADD_TASK_FILE',
  'DELETE_TASK_FILE',
  'SET_SELECTED_TASK',
  'DELETE_TASK',
  'UPDATE_TASK',
  'UPDATE_TASKS'
]
