export default [
  'GET_TASKS',
  'CHANGE_TASK_STATUS',
  'CHANGE_NEEDS_ATTENTION',
  'CREATE_TASK',
  'ADD_ATTACHMENT',
  'DELETE_ATTACHMENT',
  'SET_SELECTED_TASK',
  'DELETE_TASK',
  'UPDATE_TASK',
  'UPDATE_TASKS'
]
