export const MOVE_MAP = 'MOVE_MAP'

export const SET_MAP_ZOOM = 'SET_MAP_ZOOM'

export const SET_MAP_PROPS = 'SET_MAP_PROPS'

export const SET_POLYGON = 'SET_POLYGON'
export const REMOVE_POLYGON = 'REMOVE_POLYGON'
export const ACTIVE_DRAWING = 'ACTIVE_DRAWING'
export const INACTIVE_DRAWING = 'INACTIVE_DRAWING'

export const TOGGLE_MAP_DRAWING = 'TOGGLE_MAP_DRAWING'

export const SET_MAP_ZOOM_IN = 'SET_MAP_ZOOM_IN'
export const SET_MAP_ZOOM_OUT = 'SET_MAP_ZOOM_OUT'

export const SET_ON_MAP_AUTO_MOVE = 'SET_ON_MAP_AUTO_MOVE'
export const SET_OFF_MAP_AUTO_MOVE = 'SET_OFF_MAP_AUTO_MOVE'

export const START_GET_USER_LOCATION = 'START_GET_USER_LOCATION'
export const GET_USER_LOCATION_DONE = 'GET_USER_LOCATION_DONE'
