import { MarketLocation } from './types'

export const MARKET_LOCATIONS: MarketLocation[] = [
  { label: 'Alamance County', value: '9,58,ALCO' },
  { label: 'Allentown, PA', value: '9,113,ALLN' },
  { label: 'Austin, TX', value: '8,363,ASTN' },
  { label: 'Baton Rouge', value: '6,42,BATR' },
  { label: 'Beaumont, TX', value: '6,385,BMNT' },
  { label: 'Birmingham', value: '6,68,BIRM' },
  { label: 'BRIGHT', value: '9,60,SCPA' },
  { label: 'Brunswick, NC', value: '9,307,NCR' },
  { label: 'Bryan/College Station', value: '6,309,BRCS' },
  { label: 'Buffalo', value: '8,33,BUFF' },
  { label: 'California', value: '11,379,CALI' },
  { label: 'Central TX MLS', value: '8,28,SAN' },
  { label: 'Chattanooga', value: '8,31,CHAT' },
  { label: 'Chicago', value: '11,18,CHIC' },
  { label: 'Citrus County', value: '9,29,WFLA' },
  { label: 'Cleveland/Yes-MLS', value: '8,32,CLEV' },
  { label: 'Columbus', value: '11,17,CLBS' },
  { label: 'Columbus, IN', value: '11,15,INDY' },
  { label: 'Cookeville', value: '8,349,COOK' },
  { label: 'Crystal Coast', value: '9,371,NBMH' },
  { label: 'Dallas/Fort Worth', value: '6,1,DFW' },
  { label: 'Denver/Front Range', value: '8,27,DEN' },
  { label: 'Detroit', value: '8,263,DETR' },
  { label: 'Erie', value: '8,261,PENN' },
  { label: 'Erie/Penn', value: '8,261,PENN' },
  { label: 'Fayetteville', value: '9,10,FYTV' },
  { label: 'Florida', value: '9,29,WFLA' },
  { label: 'Fort Wayne', value: '11,74,FTWA' },
  { label: 'Golden Triangle, MS', value: '8,343,GTR-S' },
  { label: 'Greater Toronto Area', value: '13,377,GTA' },
  { label: 'Greenville', value: '9,11,GRNV' },
  { label: 'Greenville-Pitt', value: '9,56,GVPI' },
  { label: 'Heartland FL', value: '9,29,WFLA' },
  { label: 'Hickory', value: '9,46,HCKY' },
  { label: 'Hot Springs, AR', value: '6,3,LRAR' },
  { label: 'Houston', value: '6,22,HSTN' },
  { label: 'Indian River', value: '9,29,WFLA' },
  { label: 'Indianapolis', value: '11,15,INDY' },
  { label: 'Jackson, MS', value: '8,351,JAXMS' },
  { label: 'Jackson, TN', value: '8,38,JAKN' },
  { label: 'Jacksonville,NC', value: '9,239,JKNC' },
  { label: 'Johnson City', value: '8,331,JCI' },
  { label: 'Jonesboro, AR', value: '6,329,JBO' },
  { label: 'Kansas City', value: '11,12,KC' },
  { label: 'Knox County', value: '11,17,CLBS' },
  { label: 'Knoxville', value: '8,36,KNOX' },
  { label: 'Lafayette, IN', value: '11,291,LFIN' },
  { label: 'Lafayette, LA', value: '6,84,LFYT' },
  { label: 'Lake Charles, LA', value: '6,295,LKCH' },
  { label: 'Laredo, TX', value: '8,383,LRDO' },
  { label: 'Lawrence, KS', value: '11,269,LAWR' },
  { label: 'Little Rock', value: '6,3,LRAR' },
  { label: 'Long Island', value: '9,25,LNGI' },
  { label: 'Louisville, KY', value: '11,62,LOKY' },
  { label: 'Lynchburg', value: '9,40,LBVA' },
  { label: 'Madison', value: '11,52,MADI' },
  { label: 'Manhattan, KS', value: '11,375,MHTN' },
  { label: 'Mansfield', value: '11,381,MNFLD' },
  { label: 'Maryland/ BRIGHT', value: '9,60,SCPA' },
  { label: 'Massachusetts', value: '9,24,MASS' },
  { label: 'McAllen', value: '8,37,MCAL' },
  { label: 'Memphis', value: '8,34,MEM' },
  { label: 'Mid-Kansas MLS', value: '11,387,HUTC' },
  { label: 'Milwaukee', value: '11,88,MLWK' },
  { label: 'Minneapolis/St. Paul', value: '11,19,MNSP' },
  { label: 'MLS Tech', value: '6,313,TLSA' },
  { label: 'Monroe, LA', value: '6,107,MONR' },
  { label: 'Myrtle Beach', value: '9,70,MYRB' },
  { label: 'Nashville', value: '8,30,NASH' },
  { label: 'NCR/Topsail Island', value: '9,239,JKNC' },
  { label: 'New Bern/Morehead', value: '9,371,NBMH' },
  { label: 'New Orleans', value: '6,105,NORL' },
  { label: 'North Carolina Regional', value: '9,307,NCR' },
  { label: 'North Virginia/BRIGHT', value: '9,60,SCPA' },
  { label: 'Oklahoma City, OK', value: '6,86,OKC' },
  { label: 'Omaha', value: '11,72,OMAH' },
  { label: 'Oxford, MS', value: '8,357,OXF' },
  { label: 'Peoria, IL', value: '11,64,PEOR' },
  { label: 'Philadelphia/BRIGHT', value: '9,60,SCPA' },
  { label: 'Pikes Peak', value: '8,27,DEN' },
  { label: 'Pueblo, CO', value: '8,111,PUEB' },
  { label: 'REALTORS Association of Edmonton', value: '13,389,RAE' },
  { label: 'Reno, NV', value: '8,109,RENO' },
  { label: 'Rochester', value: '8,33,BUFF' },
  { label: 'Rockford, IL', value: '11,76,ROKF' },
  { label: 'Rocky Mount', value: '9,307,NCR' },
  { label: 'Rogers, AR', value: '6,355,ROGAR' },
  { label: 'Salt Lake City/Wasatch Range', value: '8,39,SLC' },
  { label: 'San Antonio', value: '8,28,SAN' },
  { label: 'Sanford', value: '9,10,FYTV' },
  { label: 'Savannah, GA', value: '9,305,SVNH' },
  { label: 'Scioto Valley', value: '11,17,CLBS' },
  { label: 'Shreveport', value: '6,2,SHRV' },
  { label: 'South Central PA/BRIGHT', value: '9,60,SCPA' },
  { label: 'Southern Ohio', value: '11,101,SOOH' },
  { label: 'St Louis', value: '11,13,STL' },
  { label: 'Sudbury Real Estate Board', value: '13,388,SREB' },
  { label: 'SW Iowa', value: '11,72,OMAH' },
  { label: 'Topeka', value: '11,267,TOPK' },
  { label: 'Tulsa, OK', value: '6,313,TLSA' },
  { label: 'Tupelo', value: '8,337,TUP' },
  { label: 'Washington, DC/BRIGHT', value: '9,60,SCPA' },
  { label: 'West Penn', value: '8,261,PENN' },
  { label: 'Westchester', value: '9,23,WCHS' },
  { label: 'Western Colorado', value: '8,257,WCOL' },
  { label: 'Wilmington', value: '9,8,WILM' },
  { label: 'Wilson, NC', value: '9,307,NCR' },
  { label: 'Yes-MLS', value: '8,32,CLEV' }
]
