export const FETCH_ALERTS_REQUEST = 'FETCH_ALERTS_REQUEST'
export const FETCH_ALERTS_SUCCESS = 'FETCH_ALERTS_SUCCESS'
export const FETCH_ALERTS_FAILURE = 'FETCH_ALERTS_FAILURE'

export const SET_SELECTED_ALERT = 'SET_SELECTED_ALERT'
