export const FETCH_ALERTS_REQUEST = 'FETCH_ALERTS_REQUEST'
export const FETCH_ALERTS_SUCCESS = 'FETCH_ALERTS_SUCCESS'
export const FETCH_ALERTS_FAILURE = 'FETCH_ALERTS_FAILURE'

export const SET_SELECTED_ALERT_ID = 'SET_SELECTED_ALERT_ID'

export const FETCH_ALERT_FEED_REQUEST = 'FETCH_ALERT_FEED_REQUEST'
export const FETCH_ALERT_FEED_SUCCESS = 'FETCH_ALERT_FEED_SUCCESS'
export const FETCH_ALERT_FEED_FAILURE = 'FETCH_ALERT_FEED_FAILURE'

export const CLEAR_ALERT_NOTIFICATION = 'CLEAR_ALERT_NOTIFICATION'

export const CLEAR_ALERT_NOTIFICATION_REQUEST =
  'CLEAR_ALERT_NOTIFICATION_REQUEST'

export const CLEAR_ALERT_NOTIFICATION_SUCCESS =
  'CLEAR_ALERT_NOTIFICATION_SUCCESS'

export const CLEAR_ALERT_NOTIFICATION_FAILURE =
  'CLEAR_ALERT_NOTIFICATION_FAILURE'
