export const UPDATE_EMAIL_TEMPLATE = 'UPDATE_EMAIL_TEMPLATE'
export const DELETE_EMAIL_TEMPLATE = 'DELETE_EMAIL_TEMPLATE'

export const FETCH_EMAIL_TEMPLATES_REQUEST = 'FETCH_EMAIL_TEMPLATES_REQUEST'
export const FETCH_EMAIL_TEMPLATES_SUCCESS = 'FETCH_EMAIL_TEMPLATES_SUCCESS'
export const FETCH_EMAIL_TEMPLATES_FAILURE = 'FETCH_CHANGE_LISTING_FOLLOW_FAILURE'
