export const REQUEST_GLOBAL_TRIGGERS = 'REQUEST_GLOBAL_TRIGGERS'
export const REQUEST_GLOBAL_TRIGGERS_FAILED = 'REQUEST_GLOBAL_TRIGGERS_FAILED'
export const SET_GLOBAL_TRIGGER = 'SET_GLOBAL_TRIGGER'
export const SET_GLOBAL_TRIGGERS = 'SET_GLOBAL_TRIGGERS'
