export default {
  ADD_CONTACT: 'CONTACTS__ADD',
  GET_CONTACTS: 'CONTACTS__ALL',
  GET_TAGS: 'CONTACTS__GET_TAGS',
  ADD_NOTE: 'CONTACTS__ADD_NOTE',
  GET_TIMELINE: 'CONTACTS__GET_TIMELINE',
  UPSERT_ATTRIBUTES: 'CONTACTS__UPSERT_ATTRIBUTES',
  DELETE_ATTRIBUTE: 'CONTACTS__DELETE_ATTRIBUTE'
}
