
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'
export const RECEIVE_FAVORITES = 'RECEIVE_FAVORITES'
export const FETCH_FAVORITES_REQUEST = 'FETCH_FAVORITES_REQUEST'
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS'
export const FETCH_FAVORITES_FAILURE = 'FETCH_FAVORITES_FAILURE'

