
export const FETCH_WIDGET_LISTING_REQUEST = 'FETCH_WIDGET_LISTING_REQUEST'
export const FETCH_WIDGET_LISTING_SUCCESS = 'FETCH_WIDGET_LISTING_SUCCESS'
export const FETCH_WIDGET_LISTING_FAILURE = 'FETCH_WIDGET_LISTING_FAILURE'

