import _ from 'underscore'

export function stateToAbbreviated(stateName) {
  return _.findKey(STATES, name => name === stateName)
}

export const STREET_PREFIX = ['SW', 'S', 'SE', 'E', 'NW', 'W', 'NE', 'N']

export const STATES = {
  AK: 'Alaska',
  AL: 'Alabama',
  AR: 'Arkansas',
  AZ: 'Arizona',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DC: 'District of Columbia',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  IA: 'Iowa',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  MA: 'Massachusetts',
  MD: 'Maryland',
  ME: 'Maine',
  MI: 'Michigan',
  MN: 'Minnesota',
  MO: 'Missouri',
  MS: 'Mississippi',
  MT: 'Montana',
  NC: 'North Carolina',
  ND: 'North Dakota',
  NE: 'Nebraska',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NV: 'Nevada',
  NY: 'New York',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VA: 'Virginia',
  VT: 'Vermont',
  WA: 'Washington',
  WI: 'Wisconsin',
  WV: 'West Virginia',
  WY: 'Wyoming'
}

export const STREET_SUFFIX = [
  'Alley',
  'Avenue',
  'Bend',
  'Bluff',
  'Boulevard',
  'Branch',
  'ByPass',
  'Circle',
  'Cliff',
  'Corner',
  'Court',
  'Cove',
  'Creek',
  'Crossing',
  'Drive',
  'Expy',
  'Extension',
  'Freeway',
  'Gardens',
  'Glen',
  'Grove',
  'Heights',
  'Highway',
  'Hill',
  'Hollow',
  'Junction',
  'Landing',
  'Lane',
  'Loop',
  'Manor',
  'Meadows',
  'Park',
  'Parkway',
  'Pass',
  'Path',
  'Pike',
  'Place',
  'Plaza',
  'Point',
  'Ridge',
  'Road',
  'Row',
  'Run',
  'Shore',
  'Springs',
  'Spur',
  'Square',
  'Street',
  'Terrace',
  'Trace',
  'Trail',
  'Valley',
  'View',
  'Village',
  'Ville',
  'Vista',
  'Walk',
  'Way'
]

export const COUNTIES = [
  'Anderson',
  'Andrews',
  'Angelina',
  'Aransas',
  'Archer',
  'Armstrong',
  'Atascosa',
  'Austin',
  'Bailey',
  'Bandera',
  'Bastrop',
  'Baylor',
  'Bee',
  'Bell',
  'Bexar',
  'Blanco',
  'Borden',
  'Bosque',
  'Bowie',
  'Brazoria',
  'Brazos',
  'Brewster',
  'Briscoe',
  'Brooks',
  'Brown',
  'Burleson',
  'Burnet',
  'Caldwell',
  'Calhoun',
  'Callahan',
  'Cameron',
  'Camp',
  'Carson',
  'Cass',
  'Castro',
  'Chambers',
  'Cherokee',
  'Childress',
  'Clay',
  'Cochran',
  'Coke',
  'Coleman',
  'Collin',
  'Collingsworth',
  'Colorado',
  'Comal',
  'Comanche',
  'Concho',
  'Cooke',
  'Coryell',
  'Cottle',
  'Crane',
  'Crockett',
  'Crosby',
  'Culberson',
  'Dallam',
  'Dallas',
  'Dawson',
  'Deaf Smith',
  'Delta',
  'Denton',
  'DeWitt',
  'Dickens',
  'Dimmit',
  'Donley',
  'Duval',
  'Eastland',
  'Ector',
  'Edwards',
  'El Paso',
  'Ellis',
  'Erath',
  'Falls',
  'Fannin',
  'Fayette',
  'Fisher',
  'Floyd',
  'Foard',
  'Fort Bend',
  'Franklin',
  'Freestone',
  'Frio',
  'Gaines',
  'Galveston',
  'Garza',
  'Gillespie',
  'Glasscock',
  'Goliad',
  'Gonzales',
  'Gray',
  'Grayson',
  'Gregg',
  'Grimes',
  'Guadalupe',
  'Hale',
  'Hall',
  'Hamilton',
  'Hansford',
  'Hardeman',
  'Hardin',
  'Harris',
  'Harrison',
  'Hartley',
  'Haskell',
  'Hays',
  'Hemphill',
  'Henderson',
  'Hidalgo',
  'Hill',
  'Hockley',
  'Hood',
  'Hopkins',
  'Houston',
  'Howard',
  'Hudspeth',
  'Hunt',
  'Hutchinson',
  'Irion',
  'Jack',
  'Jackson',
  'Jasper',
  'Jeff Davis',
  'Jefferson',
  'Jim Hogg',
  'Jim Wells',
  'Johnson',
  'Jones',
  'Karnes',
  'Kaufman',
  'Kendall',
  'Kenedy',
  'Kent',
  'Kerr',
  'Kimble',
  'King',
  'Kinney',
  'Kleberg',
  'Knox',
  'La Salle',
  'Lamar',
  'Lamb',
  'Lampasas',
  'Lavaca',
  'Lee',
  'Leon',
  'Liberty',
  'Limestone',
  'Lipscomb',
  'Live Oak',
  'Llano',
  'Loving',
  'Lubbock',
  'Lynn',
  'Madison',
  'Marion',
  'Martin',
  'Mason',
  'Matagorda',
  'Maverick',
  'McCulloch',
  'McLennan',
  'McMullen',
  'Medina',
  'Menard',
  'Midland',
  'Milam',
  'Mills',
  'Mitchell',
  'Montague',
  'Montgomery',
  'Moore',
  'Morris',
  'Motley',
  'Nacogdoches',
  'Navarro',
  'Newton',
  'Nolan',
  'Nueces',
  'Ochiltree',
  'Oldham',
  'Orange',
  'Outside of the US',
  'Palo Pinto',
  'Panola',
  'Parker',
  'Parmer',
  'Pecos',
  'Polk',
  'Potter',
  'Presidio',
  'Rains',
  'Randall',
  'Reagan',
  'Real',
  'Red River',
  'Reeves',
  'Refugio',
  'Roberts',
  'Robertson',
  'Rockwall',
  'Runnels',
  'Rusk',
  'Sabine',
  'San Augustine',
  'San Jacinto',
  'San Patricio',
  'San Saba',
  'Schleicher',
  'Scurry',
  'Shackelford',
  'Shelby',
  'Sherman',
  'Smith',
  'Somervell',
  'Starr',
  'State of Alabama',
  'State of Alaska',
  'State of Arizona',
  'State of Arkansas',
  'State of California',
  'State of Colorado',
  'State of Connecticut',
  'State of Florida',
  'State of Georgia',
  'State of Idaho',
  'State of Illinois',
  'State of Indiana',
  'State of Kansas',
  'State of Kentucky',
  'State of Louisiana',
  'State of Maine',
  'State of Maryland',
  'State of Massachusetts',
  'State of Michigan',
  'State of Minnesota',
  'State of Mississippi',
  'State of Missouri',
  'State of Montana',
  'State of Nevada',
  'State of New Jersey',
  'State of New Mexico',
  'State of New York',
  'State of North Carolina',
  'State of North Dakota',
  'State of Ohio',
  'State of Oklahoma',
  'State of Oregon',
  'State of Pennsylvania',
  'State of South Dakota',
  'State of Tennessee',
  'State of Virginia',
  'State of Washington',
  'State of West Virginia',
  'State of Wisconsin',
  'State of Wyoming',
  'Stephens',
  'Sterling',
  'Stonewall',
  'Sutton',
  'Swisher',
  'Tarrant',
  'Taylor',
  'Terrell',
  'Terry',
  'Throckmorton',
  'Titus',
  'Tom Green',
  'Travis',
  'Trinity',
  'Tyler',
  'Upshur',
  'Upton',
  'Uvalde',
  'Val Verde',
  'Van Zandt',
  'Victoria',
  'Walker',
  'Waller',
  'Ward',
  'Washington',
  'Webb',
  'Wharton',
  'Wheeler',
  'Wichita',
  'Wilbarger',
  'Willacy',
  'Williamson',
  'Wilson',
  'Winkler',
  'Wise',
  'Wood',
  'Yoakum',
  'Young',
  'Zapata',
  'Zavala'
]
