export const FETCH_FILTER_SEGMENTS = 'FETCH_FILTER_SEGMENTS'
export const FETCH_FILTER_SEGMENTS_SUCCESS = 'FETCH_FILTER_SEGMENTS_SUCCESS'
export const FETCH_FILTER_SEGMENTS_FAILURE = 'FETCH_FILTER_SEGMENTS_FAILURE'
export const CHANGE_ACTIVE_FILTER_SEGMENT = 'CHANGE_ACTIVE_FILTER_SEGMENT'

export const SAVE_FILTER_SEGMENTS = 'SAVE_FILTER_SEGMENTS'
export const DELETE_FILTER_SEGMENTS = 'DELETE_FILTER_SEGMENTS'
