export const TOGGLE_FILTERS_AREA = 'TOGGLE_FILTERS_AREA'

export const ACTIVE_SOLD_STATUS = 'ACTIVE_SOLD_STATUS'
export const ACTIVE_ACTIVE_STATUS = 'ACTIVE_ACTIVE_STATUS'
export const ACTIVE_OPEN_HOUSES_STATUS = 'ACTIVE_OPEN_HOUSES_STATUS'
