export const TOGGLE_FILTERS_AREA = 'TOGGLE_FILTERS_AREA'

export const ACTIVE_SOLD_STATUS = 'ACTIVE_SOLD_STATUS'
export const ACTIVE_PENDING_STATUSES = 'ACTIVE_PENDING_STATUSES'
export const ACTIVE_OPEN_HOUSES_STATUS = 'ACTIVE_OPEN_HOUSES_STATUS'
