export const SET_SHOWING_TOTAL_NOTIFICATIONS_COUNT =
  'SET_SHOWING_TOTAL_NOTIFICATIONS_COUNT'

export const DECREASE_SHOWING_TOTAL_NOTIFICATIONS_COUNT =
  'DECREASE_SHOWING_TOTAL_NOTIFICATIONS_COUNT'

export const INCREASE_SHOWING_TOTAL_NOTIFICATIONS_COUNT =
  'INCREASE_SHOWING_TOTAL_NOTIFICATIONS_COUNT'
