declare interface AlertFilter {
  minimum_price?: number
  maximum_price?: number
  minimum_bedrooms?: number
  minimum_bathrooms?: number
  minimum_square_meters?: number
  maximum_square_meters?: number
  created_by?: UUID
  points?: ILocation[]
  minimum_lot_square_meters?: number
  maximum_lot_square_meters?: number
  minimum_year_built?: number
  maximum_year_built?: number
  pool?: boolean
  pets?: boolean
  number_of_pets_allowed?: number
  application_fee?: boolean
  appliances?: boolean
  furnished?: boolean
  fenced_yard?: boolean
  title?: string
  property_types: IPropertyType[]
  property_subtypes: IPropertySubtype[]
  listing_statuses?: IListingStatus[]
  open_house?: boolean
  minimum_sold_date?: number
  excluded_listing_ids?: UUID[]
  mls_areas?: unknown[]
  postal_codes?: unknown[]
  search?: string
  limit?: number
}
