declare type IListingStatus =
  | 'Active'
  | 'Lease'
  | 'Coming Soon'
  | 'Pending'
  | 'Active Kick Out'
  | 'Active Contingent'
  | 'Active Option Contract'
  | 'Lease Contract'
  | 'Sold'
  | 'Leased'
  | 'Expired'
  | 'Archived'
  | 'Cancelled'
  | 'Contract Terminated'
  | 'Withdrawn'
  | 'Temp Off Market'
  | 'Withdrawn Sublisting'
