export default [
  'GET_ROOMS',
  'CREATE_ROOM',
  'UPDATE_ROOM_TIME',
  'REMOVE_ROOM',
  'ADD_MEMBERS',
  'ACKNOWLEDGE_ROOM',
  'UPDATE_ROOM_NOTIFICATIONS',
  'RESET_ROOM_NOTIFICATIONS',
  'ADD_MESSAGE_TYPING',
  'REMOVE_MESSAGE_TYPING'
]
