// with json.parse + stringify you can bypass the typechecker.
// this is needed because there are a lot of desync between the local types and the server response.

const createMockListing = (): IListing =>
  JSON.parse(
    JSON.stringify({
      type: 'listing',
      id: 'f69ff932-8b6e-11ec-b50c-0aa41e28002f',
      property_id: 'f69c93c8-8b6e-11ec-b50c-0aa41e28002f',
      created_at: 1644606924.198537,
      updated_at: 1673469567.459401,
      price: 165000000,
      matrix_unique_id: '1725384964',
      original_price: 165000000,
      last_price: null,
      status: 'Active',
      association_fee: null,
      mls_number: '22-125547',
      association_fee_frequency: null,
      association_fee_includes: null,
      unexempt_taxes: null,
      financing_proposed: null,
      list_office_mui: '917156277',
      list_office_mls_id: null,
      list_office_name: 'Hilton & Hyland',
      list_office_phone: '310-278-3311',
      possession: '',
      co_list_office_mui: null,
      co_list_office_mls_id: null,
      co_list_office_name: null,
      co_list_office_phone: null,
      selling_office_mui: null,
      selling_office_mls_id: null,
      selling_office_name: null,
      selling_office_phone: null,
      co_selling_office_mui: null,
      co_selling_office_mls_id: null,
      co_selling_office_name: null,
      co_selling_office_phone: null,
      list_agent_mui: '1236144817',
      list_agent_direct_work_phone: '310-278-3311',
      list_agent_email: 'drew@drewfenton.com',
      list_agent_full_name: 'Drew Fenton',
      list_agent_mls_id: null,
      co_list_agent_mui: null,
      co_list_agent_direct_work_phone: null,
      co_list_agent_email: null,
      co_list_agent_full_name: 'undefined undefined',
      co_list_agent_mls_id: null,
      selling_agent_mui: null,
      selling_agent_direct_work_phone: null,
      selling_agent_email: null,
      selling_agent_full_name: null,
      selling_agent_mls_id: null,
      co_selling_agent_mui: null,
      co_selling_agent_direct_work_phone: null,
      co_selling_agent_email: null,
      co_selling_agent_full_name: null,
      co_selling_agent_mls_id: null,
      listing_agreement: null,
      mls_area_major: null,
      mls_area_minor: null,
      mls_name: 'CLAW',
      matrix_modified_dt: '2022-07-29T22:56:48.000Z',
      showing_instructions_type: null,
      tax_legal_description: null,
      keybox_type: null,
      keybox_number: null,
      close_date: null,
      close_price: null,
      deleted_at: null,
      dom: 372,
      cdom: null,
      buyers_agency_commission: null,
      sub_agency_commission: null,
      list_date: null,
      showing_instructions: '24-hr Notice,Call LA 1,Call LA 2',
      appointment_phone: null,
      appointment_phone_ext: null,
      appointment_call: null,
      occupancy: null,
      private_remarks: null,
      photos_checked_at: null,
      application_fee_yn: null,
      revision: 1,
      mls: 'CLAW',
      transaction_type: 'Sale',
      usage_type: 'Unknown',
      structure_type: null,
      original_mls_property_type: 'Residential',
      original_mls_property_subtype: null,
      original_mls_status: 'Active',
      is_address_public: true,
      parcel_number: null,
      public_display: true,
      annual_tax: null,
      virtual_tour: null,
      sub_agency_offered: null,
      transaction_broker_commission: null,
      compensation_based_on: null,
      co_list_agent2_mui: null,
      co_list_agent2_direct_work_phone: null,
      co_list_agent2_email: null,
      co_list_agent2_full_name: null,
      co_list_agent2_mls_id: null,
      co_list_agent3_mui: null,
      co_list_agent3_direct_work_phone: null,
      co_list_agent3_email: null,
      co_list_agent3_full_name: null,
      co_list_agent3_mls_id: null,
      co_selling_agent2_mui: null,
      co_selling_agent2_direct_work_phone: null,
      co_selling_agent2_email: null,
      co_selling_agent2_full_name: null,
      co_selling_agent2_mls_id: null,
      co_selling_agent3_mui: null,
      co_selling_agent3_direct_work_phone: null,
      co_selling_agent3_email: null,
      co_selling_agent3_full_name: null,
      co_selling_agent3_mls_id: null,
      list_agent: {
        id: '426d272e-8f00-11ec-954a-0271a4acc769',
        email: 'drew@drewfenton.com',
        mlsid: 'X73293',
        fax: null,
        full_name: 'Drew Fenton',
        first_name: 'Drew',
        last_name: 'Fenton',
        middle_name: null,
        phone_number: '310-623-3622',
        nar_number: null,
        office_mui: '763144060',
        status: 'Active',
        office_mlsid: 'X83363',
        work_phone: '310-623-3600',
        generational_name: null,
        matrix_unique_id: '1236144817',
        updated_at: 1668486938.158923,
        deleted_at: null,
        created_at: 1644999181.886447,
        mls: 'CLAW',
        license_number: '01317962',
        designation: null,
        nrds: null,
        type: 'agent',
        office_id: 'a3ea50d2-4592-11ed-9e3e-0e4bb9531bd9',
        secret_questions: [
          '(310) XXX-XX00',
          '(310) XXX-XX22',
          'drewxxxxxxxxxxx.com'
        ]
      },
      favorited: false,
      gallery_image_urls: [
        'https://cdn.rechat.com/fd6a44e9e00d0342e4261ffdcfa522db.jpg',
        'https://cdn.rechat.com/18d37138d8c5e06041cc6a2290e068ff.jpg',
        'https://cdn.rechat.com/7118fc45ac170d5734e0602c029339c1.jpg',
        'https://cdn.rechat.com/100e0bcbd833c1c03f4d3c4c99167936.jpg',
        'https://cdn.rechat.com/c0015f6140b8402eb0c954f4b4625ddf.jpg',
        'https://cdn.rechat.com/0c2b531637d2492a08a8524340795006.jpg',
        'https://cdn.rechat.com/1c0f0f382adabe2066753e6feab69b46.jpg',
        'https://cdn.rechat.com/1cfc1016402c395b76fae3af02c4bf9e.jpg',
        'https://cdn.rechat.com/761731bd05b137ebb3d7080c1116ed48.jpg',
        'https://cdn.rechat.com/c25a078dd2cef04003bff0396e143747.jpg',
        'https://cdn.rechat.com/dfc51abfc02d2dd6feee1f9956b19e2c.jpg',
        'https://cdn.rechat.com/b7557b5c356cb26dbed872a7fc911f61.jpg',
        'https://cdn.rechat.com/ecb6e298bf114d7f4e219ddbb76741d4.jpg',
        'https://cdn.rechat.com/a91a7e3447117e754744f0e4dd4505d8.jpg',
        'https://cdn.rechat.com/088d63b7f1920c29e8c97b7cf3a208df.jpg',
        'https://cdn.rechat.com/8adf8e77d1acc50833df62bf8da76b6b.jpg',
        'https://cdn.rechat.com/25a8278e9274a3f0f8ced66a9d2e32d8.jpg',
        'https://cdn.rechat.com/f862e33afb74b28ee477c5b923343ee7.jpg',
        'https://cdn.rechat.com/a2b8fa7dbdceb2fa2ea8de369474b74d.jpg',
        'https://cdn.rechat.com/92d8ec3df6016c5b9852e144b021b1e6.jpg',
        'https://cdn.rechat.com/1a0df1dc769b0f446ee0b6c78c68213e.jpg',
        'https://cdn.rechat.com/05fe6363cd89fc9b85c081e55634a884.jpg',
        'https://cdn.rechat.com/6037416508f1a2071a2d14209c7c3c5f.jpg',
        'https://cdn.rechat.com/e2539d4538941c3b55899b05c4a64992.jpg',
        'https://cdn.rechat.com/4bc3109f53dab75ef69a9b36a7e76ca3.jpg',
        'https://cdn.rechat.com/c2d04f9995c588ba2062d0afbb085e05.jpg',
        'https://cdn.rechat.com/28232ab335778394491e04dade348905.jpg',
        'https://cdn.rechat.com/8ad24b5369079d037243b39028d42f09.jpg'
      ],
      cover_image_url:
        'https://cdn.rechat.com/fd6a44e9e00d0342e4261ffdcfa522db.jpg',
      open_houses: null,
      property: {
        type: 'property',
        id: 'f69c93c8-8b6e-11ec-b50c-0aa41e28002f',
        bedroom_count: 14,
        bathroom_count: 9.9,
        address_id: 'f6951bd4-8b6e-11ec-b50c-0aa41e28002f',
        description:
          '"The Manor" An unparalleled offering, an unrivaled setting, a showplace of the highest caliber. The Manor is undoubtedly one of the finest estates in the World. Majestically sited on 4.68 acres in the heart of Holmby Hills, The Manor offers complete privacy bordering the Los Angeles Country Club. Entirely clad in limestone and comprised of over 56,000sqft, The Manor offers every amenity imaginable. From bowling alleys to beauty salons, rolling lawns to rose gardens, a legendary library to professional screening room: the options are vast and endless. A rare opportunity to acquire one of the most important estates ever created.',
        square_meters: 5249.02683971423,
        created_at: 1644606924.176281,
        updated_at: 1673469567.338464,
        matrix_unique_id: 1725384964,
        property_type: 'Residential',
        property_subtype: 'RES-Single Family',
        lot_square_meters: 18622.339486617304,
        year_built: 1990,
        exterior_features: [],
        interior_features: [],
        fireplace_features: [
          'Dining',
          'Family Room',
          'Library',
          'Living Room',
          'Master Bedroom'
        ],
        lot_features: null,
        parking_features: [
          'Oversized',
          'Gated',
          'Garage - 4+ Car',
          'Tandem',
          'Parking for Guests',
          'Driveway'
        ],
        pool_features: ['Heated', 'In Ground'],
        security_features: null,
        parking_spaces_covered_total: null,
        half_bathroom_count: 19,
        full_bathroom_count: 8,
        heating: [],
        flooring: ['Carpet', 'Mixed', 'Hardwood', 'Stone'],
        utilities: null,
        utilities_other: null,
        architectural_style: null,
        number_of_stories: 3,
        number_of_parking_spaces: null,
        garage_length: null,
        garage_width: null,
        number_of_dining_areas: null,
        number_of_living_areas: null,
        fireplaces_total: null,
        lot_number: null,
        soil_type: null,
        construction_materials: null,
        foundation_details: '',
        roof: null,
        pool_yn: true,
        handicap_yn: null,
        elementary_school_name: null,
        intermediate_school_name: null,
        high_school_name: null,
        junior_high_school_name: null,
        middle_school_name: null,
        primary_school_name: null,
        senior_high_school_name: null,
        school_district: null,
        subdivision_name: null,
        appliances_yn: null,
        green_building_certification: null,
        green_energy_efficient: null,
        lot_size: null,
        lot_size_area: 4.6017,
        lot_size_dimensions: null,
        number_of_pets_allowed: null,
        number_of_units: null,
        pets_yn: null,
        deleted_at: null,
        furnished_yn: null,
        fenced_yard_yn: null,
        block: null,
        mls: 'CLAW',
        pets_policy: null,
        amenities: [],
        address: {
          title: '',
          subtitle: '',
          street_number: '594',
          street_name: 'MAPLETON',
          city: 'LOS ANGELES',
          state: 'California',
          state_code: 'CA',
          postal_code: '90024',
          neighborhood: null,
          id: 'f6951bd4-8b6e-11ec-b50c-0aa41e28002f',
          street_suffix: 'DR',
          unit_number: null,
          country: 'United States',
          country_code: 'USA',
          created_at: 1644606924.127335,
          updated_at: 1673469567.259353,
          location_google: null,
          matrix_unique_id: 1725384964,
          geocoded: true,
          geo_source: 'MLS',
          partial_match_google: false,
          county_or_parish: 'Los Angeles',
          direction: 'South of Sunset, East of Beverly Glen.',
          street_dir_prefix: 'S',
          street_dir_suffix: null,
          street_number_searchable: '594',
          geo_source_formatted_address_google: null,
          geocoded_google: null,
          geocoded_bing: null,
          location_bing: null,
          geo_source_formatted_address_bing: null,
          geo_confidence_google: null,
          geo_confidence_bing: null,
          location: {
            type: 'location',
            longitude: -118.428287,
            latitude: 34.07333
          },
          approximate: true,
          corrupted: false,
          corrupted_google: null,
          corrupted_bing: null,
          deleted_at: null,
          mls: 'CLAW',
          location_mapbox: null,
          geocoded_mapbox: null,
          corrupted_mapbox: null,
          geo_source_formatted_address_mapbox: null,
          geo_confidence_mapbox: null,
          type: 'address',
          full_address: '594 S MAPLETON DR LOS ANGELES, CA 90024',
          street_address: '594 S MAPLETON DR'
        }
      },
      user_listing_notification_setting: null,
      mls_display_name: 'CLAW',
      _url: 'https://app.rechat.com/dashboard/mls/f69ff932-8b6e-11ec-b50c-0aa41e28002f'
    })
  )

export default createMockListing
